<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = [
            [
                'name' => 'Alice Johnson',
                'full_name' => 'Alice Marie Johnson',
                'username' => 'alice_j',
                'email' => 'alice@university.edu',
                'fakultas' => 'Computer Science',
                'prodi' => 'Software Engineering',
                'gender' => 'female',
                'age' => 21,
                'bio' => 'Passionate about full-stack development and AI. Love coding and building innovative solutions!',
                'profile_picture' => 'https://images.unsplash.com/photo-1494790108755-2616b2e4a6d1?w=400',
                'user_type' => 'student',
                'verification_status' => 'verified',
                'qualification' => 'undergraduate',
                'looking_for' => 'friends,study_partners,networking',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
            ],
            [
                'name' => 'Bob Chen',
                'full_name' => 'Robert Chen Wei Ming',
                'username' => 'bob_chen',
                'email' => 'bob@university.edu',
                'fakultas' => 'Engineering',
                'prodi' => 'Mechanical Engineering',
                'gender' => 'male',
                'age' => 22,
                'bio' => 'Mechanical engineering student interested in robotics and automation. Also love basketball!',
                'profile_picture' => 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
                'user_type' => 'student',
                'verification_status' => 'verified',
                'qualification' => 'undergraduate',
                'looking_for' => 'friends,sports_partners',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
            ],
            [
                'name' => 'Catherine Maria',
                'full_name' => 'Catherine Maria Rodriguez',
                'username' => 'cat_maria',
                'email' => 'catherine@university.edu',
                'fakultas' => 'Arts & Design',
                'prodi' => 'Graphic Design',
                'gender' => 'female',
                'age' => 20,
                'bio' => 'Creative soul who loves photography, UI/UX design, and visual storytelling. Always exploring new art forms!',
                'profile_picture' => 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400',
                'user_type' => 'student',
                'verification_status' => 'verified',
                'qualification' => 'undergraduate',
                'looking_for' => 'creative_collaborators,friends',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
            ],
            [
                'name' => 'David Wilson',
                'full_name' => 'David Michael Wilson',
                'username' => 'david_w',
                'email' => 'david@university.edu',
                'fakultas' => 'Business',
                'prodi' => 'Business Administration',
                'gender' => 'male',
                'age' => 23,
                'bio' => 'Entrepreneur-minded business student. Interested in startups, leadership, and digital marketing.',
                'profile_picture' => 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400',
                'user_type' => 'student',
                'verification_status' => 'verified',
                'qualification' => 'undergraduate',
                'looking_for' => 'business_partners,networking,mentorship',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
            ],
            [
                'name' => 'Emma Rodriguez',
                'full_name' => 'Emma Sofia Rodriguez',
                'username' => 'emma_r',
                'email' => 'emma@university.edu',
                'fakultas' => 'Psychology',
                'prodi' => 'Clinical Psychology',
                'gender' => 'female',
                'age' => 21,
                'bio' => 'Psychology student passionate about mental health awareness and helping others. Love reading and volunteering.',
                'profile_picture' => 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400',
                'user_type' => 'student',
                'verification_status' => 'verified',
                'qualification' => 'undergraduate',
                'looking_for' => 'study_partners,volunteering,friends',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
            ],
            [
                'name' => 'Frank Kumar',
                'full_name' => 'Franklin Kumar Patel',
                'username' => 'frank_k',
                'email' => 'frank@university.edu',
                'fakultas' => 'Science',
                'prodi' => 'Physics',
                'gender' => 'male',
                'age' => 20,
                'bio' => 'Physics student fascinated by quantum mechanics and astrophysics. Also enjoy gaming and sci-fi movies.',
                'profile_picture' => 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400',
                'user_type' => 'student',
                'verification_status' => 'verified',
                'qualification' => 'undergraduate',
                'looking_for' => 'study_partners,gaming_buddies,friends',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
            ],
            [
                'name' => 'Grace Liu',
                'full_name' => 'Grace Mei-Lin Liu',
                'username' => 'grace_liu',
                'email' => 'grace@university.edu',
                'fakultas' => 'Medicine',
                'prodi' => 'General Medicine',
                'gender' => 'female',
                'age' => 21,
                'bio' => 'Pre-med student dedicated to healthcare and helping communities. Love swimming and environmental causes.',
                'profile_picture' => 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400',
                'user_type' => 'student',
                'verification_status' => 'verified',
                'qualification' => 'undergraduate',
                'looking_for' => 'study_partners,sports_partners,volunteering',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
            ],
            [
                'name' => 'Henry Park',
                'full_name' => 'Henry Joon Park',
                'username' => 'henry_p',
                'email' => 'henry@university.edu',
                'fakultas' => 'Computer Science',
                'prodi' => 'Data Science',
                'gender' => 'male',
                'age' => 22,
                'bio' => 'Data science enthusiast working on machine learning projects. Also passionate about finance and investments.',
                'profile_picture' => 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=400',
                'user_type' => 'student',
                'verification_status' => 'verified',
                'qualification' => 'undergraduate',
                'looking_for' => 'research_partners,networking,friends',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
            ],
            [
                'name' => 'Isabel Santos',
                'full_name' => 'Isabel Carmen Santos',
                'username' => 'isabel_s',
                'email' => 'isabel@university.edu',
                'fakultas' => 'Arts & Design',
                'prodi' => 'Music Performance',
                'gender' => 'female',
                'age' => 20,
                'bio' => 'Music student specializing in piano and composition. Love dancing, film, and cultural arts.',
                'profile_picture' => 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=400',
                'user_type' => 'student',
                'verification_status' => 'verified',
                'qualification' => 'undergraduate',
                'looking_for' => 'creative_collaborators,friends,cultural_activities',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
            ],
            [
                'name' => 'Jack Thompson',
                'full_name' => 'Jackson Michael Thompson',
                'username' => 'jack_t',
                'email' => 'jack@university.edu',
                'fakultas' => 'Sports Science',
                'prodi' => 'Sports Management',
                'gender' => 'male',
                'age' => 21,
                'bio' => 'Sports management student and former football captain. Passionate about fitness, coaching, and team leadership.',
                'profile_picture' => 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400',
                'user_type' => 'student',
                'verification_status' => 'verified',
                'qualification' => 'undergraduate',
                'looking_for' => 'sports_partners,team_members,leadership',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
            ],
        ];

        foreach ($users as $user) {
            User::create($user);
        }
    }
}